### ISSUE TITLE
gulp test does not work once angultics is installed

### ISSUE THREAD

**Issue by lebsral** [luisfarzati/angulartics#329]
Hi,

I have a project that has test fail whenever I add in angulartics.  
To demonstrate I created a new yeoman project. 
yo gulp-angular
 Karma tests worked fine. 
Then did just 
bower install angulartics --save

The gulp test fails

You can see for yourself here.
https://github.com/lebsral/ticsonly

Larss-MBP:ticsonly lars$ gulp test
[10:49:39] Using gulpfile ~/mycode/ticsonly/gulpfile.js
[10:49:39] Starting 'scripts'...
[10:49:39] all files 2.85 kB
[10:49:39] Finished 'scripts' after 374 ms
[10:49:39] Starting 'test'...
INFO [karma]: Karma v0.12.31 server started at http://localhost:9876/
INFO [launcher]: Starting browser PhantomJS
WARN [watcher]: Pattern "/Users/lars/mycode/ticsonly/src/**/*.mock.js" does not match any file.
INFO [PhantomJS 1.9.8 (Mac OS X)]: Connected on socket 4enTfAnMXLsyVQL6KufQ with id 52460829
PhantomJS 1.9.8 (Mac OS X) ERROR
  TypeError: 'undefined' is not a function (evaluating '$(window)')
  at /Users/lars/mycode/ticsonly/bower_components/waypoints/waypoints.js:25

[10:49:42] 'test' errored after 2.61 s
[10:49:42] Error: 1
    at formatError (/usr/local/lib/node_modules/gulp/bin/gulp.js:169:10)
    at Gulp.<anonymous> (/usr/local/lib/node_modules/gulp/bin/gulp.js:195:15)
    at Gulp.emit (events.js:107:17)
    at Gulp.Orchestrator._emitTaskDone (/Users/lars/mycode/ticsonly/node_modules/gulp/node_modules/orchestrator/index.js:264:8)
    at /Users/lars/mycode/ticsonly/node_modules/gulp/node_modules/orchestrator/index.js:275:23
    at finish (/Users/lars/mycode/ticsonly/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:21:8)
    at cb (/Users/lars/mycode/ticsonly/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:29:3)
    at removeAllListeners (/Users/lars/mycode/ticsonly/node_modules/karma/lib/server.js:220:7)
    at Server.<anonymous> (/Users/lars/mycode/ticsonly/node_modules/karma/lib/server.js:231:9)
    at Server.g (events.js:199:16)

I'll cross post this to the yeoman generator  (is there an official way to do that?)

**Comment by lebsral** [comment]
Or to make this more simple I created a new one here
https://github.com/lebsral/testvideo2

gulp test
fails here also

**Comment by lunks** [comment]
My first guess would be that jQuery is not installed, but required by jQuery Waypoints. Perhaps this is the issue?

**Comment by mediavrog** [comment]
related to https://github.com/luisfarzati/angulartics/issues/359 and https://github.com/luisfarzati/angulartics/issues/341 ?
